apiVersion: apps/v1
kind: Deployment
metadata:
  name: heidian-help-doc
  namespace: heidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heidian-help-doc
  template:
    metadata:
      labels:
        app: heidian-help-doc
    spec:
      containers:
      - image: ghcr.io/heidian/kf5-articles-exporter:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        name: kf5-articles-exporter
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: heidian-help-doc-svc
  namespace: heidian
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: heidian-help-doc
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heidian-help-doc-ingress
  namespace: heidian
spec:
  tls:
  - secretName: ssl-wildcard-heidianer-com
  rules:
  - host: support.heidianer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: heidian-help-doc-svc
            port:
              number: 3000
